FROM ubuntu:20.04
# ubuntu 환경으로 BE 컨테이너 구성
WORKDIR /server
COPY . /server

# python, pip 다운 및 필요한 모듈, 가상환경 다운
RUN apt-get update
RUN apt install -y python3-pip python3-dev libsndfile1 git wget
# 가상환경 실행(gunicorn)
RUN pip install virtualenv
RUN virtualenv venv
RUN . venv/bin/activate

# pip 설치
RUN pip install -r all_requirements.txt
RUN pip install numba

# celery 실행
CMD ["celry", "-A", "backend", "worker", "--pool=threads", "--loglevel-info"]