# Generated by Django 3.2.13 on 2022-05-14 15:44

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', channel.models.EncryptedCharField(max_length=500)),
                ('ssifi_response', channel.models.EncryptedCharField(max_length=500)),
                ('mode', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_key', models.CharField(max_length=100)),
            ],
        ),
    ]
